[plugins]
android-app = { id = "budgetplus.android.app" }
android-library = { id = "budgetplus.android.library" }
app-benchmark = { id = "budgetplus.app.benchmark" }
compose = { id = "budgetplus.compose" }
metro = { id = "budgetplus.metro" }
kotlin-multiplatform = { id = "budgetplus.kotlin.multiplatform" }
kotlin-serialization = { id = "budgetplus.kotlin.serialization" }
insider-app = { id = "budgetplus.insider.app" }