[plugins]
android-app = { id = "budgetplus.android.app" }
app-benchmark = { id = "budgetplus.app.benchmark" }
compose = { id = "budgetplus.compose" }
compose-multiplatform = { id = "budgetplus.compose.multiplatform" }
metro = { id = "budgetplus.metro" }
kotlin-multiplatform = { id = "budgetplus.kotlin.multiplatform" }
insider-app = { id = "budgetplus.insider.app" }